codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  ignore:
    - "src/main/java/edu.fiuba.algo3/controladores/**"
    - "src/main/java/edu.fiuba.algo3/resources/**"
    - "src/main/java/edu.fiuba.algo3/vistas/**"
  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
require_changes: no