@startuml

actor User
hide footbox
create Personaje
User -> Personaje: new()
Personaje -> Personaje: new Posicion(0, 0)


User -> Personaje: ejecutarBloque(new BloqueMoverDerecha)
create BloqueMoverDerecha
Personaje -> BloqueMoverDerecha: new()

Personaje -> BloqueMoverDerecha:  //ejecutar//(unPersonaje)

BloqueMoverDerecha --> Personaje: moverADerecha()

Personaje -> ":unaPosicion": //derechaDe//(unaPosicion: Posicion)

":unaPosicion" --> Personaje: nuevaPosicion

Personaje -> Personaje: guardarPosicion(nuevaPosicion)


@enduml