@startuml

actor User
hide footbox
activate User
create Personaje
User -> Personaje: new()

Personaje -> Personaje: new Posicion(0, 0)
activate Personaje

User -> Personaje: ejecutarBloque(new BloqueMoverDerecha)
create BloqueMoverDerecha
Personaje -> BloqueMoverDerecha: new()

Personaje -> BloqueMoverDerecha:  //ejecutar//(unPersonaje)
activate BloqueMoverDerecha
BloqueMoverDerecha --> Personaje: moverADerecha()
deactivate BloqueMoverDerecha
Personaje -> ":Posicion": //derechaDe//(unaPosicion)

":Posicion" --> Personaje: nuevaPosicion
deactivate Personaje

User -> Personaje: ejecutarBloque(new BloqueMoverAbajo)
activate Personaje
create BloqueMoverAbajo
Personaje -> BloqueMoverAbajo: new()

Personaje -> BloqueMoverAbajo:  //ejecutar//(unPersonaje)
activate BloqueMoverAbajo
BloqueMoverAbajo --> Personaje: moverAbajo()
deactivate BloqueMoverAbajo
Personaje -> ":Posicion": //abajoDe//(unaPosicion)

":Posicion" --> Personaje: nuevaPosicion
deactivate Personaje
deactivate User
@enduml
