@startuml

hide footbox
actor User

create Personaje
User -> Personaje: new()
User -> Personaje: estadoLapiz()

Personaje -> ":EstadoLapiz": dameEstado()

":EstadoLapiz" --> Personaje: "ESTADO DESACTIVADO"
Personaje --> User: "ESTADO DESACTIVADO"

@enduml