@startuml

hide footbox
actor User
activate User
create Personaje
User -> Personaje: new()
User -> Personaje: estadoLapiz()
activate Personaje
Personaje -> ":EstadoLapiz": dameEstado()
activate ":EstadoLapiz"
":EstadoLapiz" --> Personaje: "ESTADO DESACTIVADO"
deactivate ":EstadoLapiz"
Personaje --> User: "ESTADO DESACTIVADO"
deactivate Personaje
@enduml