@startuml

hide footbox
actor User

create Personaje
User -> Personaje: new()
User -> Personaje: activarLapiz()
User -> Personaje: estadoLapiz()

Personaje -> ":EstadoLapiz": dameEstado()

":EstadoLapiz" --> Personaje: "ESTADO ACTIVADO"
Personaje --> User: "ESTADO ACTIVADO"

@enduml