@startuml

hide footbox
actor User

create Personaje
User -> Personaje: new
Personaje -> Personaje: new Posicion(0, 0)
create Posicion
User -> Posicion: new Posicion(0, 0)

User -> Posicion: //compararPosiciones//(posicionCero, getPoscicion(personaje: Personaje)):  boolean

Posicion --> User: true

@enduml